rango/urls.py
from django.conf.urls import url

from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<cat_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^category/(?P<slug>[\w\-]+)/$',
        views.show_category, name="category"),
    url(r'^register/$', views.register, name='register'),
    url(r'login/$', views.user_login, name='login'),
    url(r'logout/$', views.user_logout, name='logout'),
]

tango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth.models import User
from django.db import models

from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=200)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profil_images", blank=True)

    class Meta:
        def __str__(self):
            return self.user.username

rango/forms.py
from django import forms

from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text='Enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(),
                               initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),
                               initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),
                           required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Enter the title of the page')
    url = forms.URLField(max_length=200,
                         help_text='Enter the URL of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(),
                               initial=0)

    class Meta:
        model = Page
        fields = ('title', 'url', 'views',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

from datetime import datetime


def index(request):
    categories = Category.objects.order_by('-likes')[:5]
    most_viewed_pages = Page.objects.order_by('-views')[:5]
    visitor_cookie_handler(request)
    context = {'categories': categories,
               'most_viewed_pages': most_viewed_pages}
    context['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context)
    return response


def show_category(request, slug):
    try:
        cat = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        cat = None
    context = {'category': cat}
    return render(request, 'rango/category.html', context)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, cat_slug):
    try:
        category = Category.objects.get(slug=cat_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, cat_slug)
            else:
                return show_category(request, category)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def about(request):
    return HttpResponse("Aici about<br><a href='/rango/'>Acasa</a>")


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = user_profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, user_profile_form.errors)
    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'user_profile_form': user_profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Your credentials are incorrect")
    else:
        return render(request, 'rango/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).seconds > 5:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        # visits = visits
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

rango/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title %}
    Add New Category
{% endblock title %}


{% block body %}
    <h1>Add a Category</h1>
    <div>
        <form action="{% url 'rango:add_category' %}" id="category_form" method="post">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit", name="submit" value="Create Category">
        </form>
    </div>
{% endblock body %}

rango/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title %}
    Add New Page
{% endblock title %}


{% block body %}
    {% if  category %}  
        <h1>Add a Page to category  {{ category.name}}</h1> 
        <div>
            <form action="{% url 'rango:add_page' category.slug %}" id="page_form" method="post">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit", name="submit" value="Add Page">
            </form>
        </div>
    {% else %}
        This category doesn't exist yet.
    {% endif %}
{% endblock body %}

rango/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
    <script src="{% static "js/base.js" %}"></script>
    <title>Rango - 
        {% block title %}
            HTWD
        {% endblock title %}
    </title>
</head>
<body>
    {% block sidebar %}
        {% get_category_list category %}
    {% endblock sidebar %}

    {% block body %}
        
    {% endblock body %}
    <div>
        <ul>
            {% if  user.is_authenticated %}
                <li><a href="{% url 'rango:logout'%}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'rango:register'%}">Sign Up</a></li>
                <li><a href="{% url 'rango:login'%}">Login</a></li>
            {% endif %}
            
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>

            
        </ul>
    </div>
</body>
</html>

rango/templates/rango/category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title %}
    {{ category.name}}
{% endblock title %}

{% block body %}
        {% if category %}
            <h1>{{ category.name }}</h1>
            {% if category.page_set.all %}
                <ul>
                    {% for page in category.page_set.all %}
                        <li><a href="{{ page.url }}">{{ page.title}}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages yet</strong>
            {% endif %}
        {% else %}
            <strong>There is no such category</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
{% endblock body %}

rango/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li><a href="{% url 'rango:category' c.slug %}"><strong>{{ c.name }}</strong></a></li>
            {% else %}
                <li><a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li> <strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

rango/templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles rango_template_tags %}
{% block title %}
    Home
{% endblock title %}

{% block body %}
        {% if user.is_authenticated %}
            howdy {{ user.username }}
        {% else %}
            hy there, partner!
        {% endif %}
        {% if categories %}
        <h2>Most liked categories</h2>
            <ul>
                {% for cat in categories %}
                    <li><a href="{% url "rango:category" cat.slug %}">{{ cat.name}}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories</strong>
        {% endif %}
        <a href=" {% url "rango:add_category" %} ">Add a New Category</a>
    </div>

    <div>
        {% if most_viewed_pages %}
            <h2>Most viewed pages</h2>
            <ul>
                {% for page in most_viewed_pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

	<div>
		<img src="{% static "images/lw.jpg" %}" alt="Picture of Ludwig Wittgenstein">
	</div>
    <p> visits: {{ visits }}</p>
{% endblock body %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    login
{% endblock title %}

{% block body %}
    <form id="login_form" action="{% url 'rango:login'%}" method="post">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50">
        <br>
        Password: <input type="password" name="password" value="" size="50">
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock body %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong>. Go to the <a href="{% url 'rango:index' %}">home</a> page<br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Display each form -->
            {{ user_form.as_p }}
            {{ user_profile_form.as_p }}
            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}